name: 测试action
on: push

jobs:
  job1:
    name: 工作流1
    runs-on: ubuntu-latest

    steps:
      - name: 显示当前目录
        run: pwd
      - name: 查看node版本
        run: node --version
      - name: 安装依赖
        run: npm install
