name: 测试action
on: push

jobs:
  job1:
    name: 工作流1
    runs-on: ubuntu-latest

    steps:
      - name:: 显示当前目录
        run: pwd
      - uses: actions/checkout@v3
      - run: ls
      - name: 查看node版本
        run: node --version

  job2:
    runs-on: windows-latest
    steps:
      - run: node --version
